author = Artur Tarassow
email = atecon@posteo.de
version = 0.2
date = 2024-11-01
description = Plot seasonal time-series components
tags = C22
min-version = 2024b
public = set_season_plot plot_season_plot season_plot_gui
data-requirement = needs-time-series-data
help = season_plot_help.md
sample-script = season_plot_sample.inp
gui-main = season_plot_gui
label = Season Plot
menu-attachment = MAINWIN/View/GraphVars
depends = string_utils
